# Generated by Django 6.0.3 on 2026-04-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
