# Generated by Django 6.0.3 on 2026-03-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbank',
            name='english_word',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wordbank',
            name='word',
            field=models.CharField(max_length=200),
        ),
    ]
