# Generated by Django 6.0.3 on 2026-03-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_alter_wordbank_english_word_alter_wordbank_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='release_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
